import { freezeSpecCore } from "./policy.js";
import type { JobSpec } from "./domain.js";

// Sensitive vehicle identifier: repository access must remain restricted and deliberate.
export const specCore = {purchaseMode:"CASH_PAY" as const,vehicle:{vin:"3VV2B7AX0MM103995",vinVerification:"CHECKSUM_AND_DECODED" as const,year:2021,make:"Volkswagen",model:"Tiguan",trim:"UNKNOWN" as const,adasFeatures:["FRONT_CAMERA" as const]},damage:{service:"WINDSHIELD_REPLACEMENT" as const,drivable:true},requirements:{glassPreference:"AFTERMARKET_EQUIVALENT_ACCEPTABLE" as const,calibrationRequired:"YES" as const,serviceMode:["MOBILE" as const,"IN_SHOP" as const],warrantyRequired:true},serviceArea:{postalCode:"28202",exactAddressDisclosure:"AFTER_SELECTION" as const},schedule:{windows:["weekday morning","weekday afternoon"],flexible:true},authorization:{mayGatherQuotes:true as const,mayUseVerifiedCompetitorOffer:true,mayBook:false as const,maximumTotalMinor:null},unknowns:["vehicle.trim"]};
export const specHash=freezeSpecCore(specCore);
export const CALL_BRIEF="2021 Volkswagen Tiguan, trim unknown, VIN 3VV2B7AX0MM103995. Windshield replacement for a drivable vehicle. Aftermarket equivalent glass is acceptable. Front-camera ADAS calibration is required. Mobile or in-shop service is acceptable in ZIP 28202. The schedule is flexible on weekday mornings or afternoons. Warranty is required.";
export const SPOKEN_CALL_BRIEF="I need a cash-pay windshield replacement quote for a 2021 Volkswagen Tiguan in ZIP 28202. Aftermarket-equivalent glass is acceptable, front-camera calibration and a warranty are required, and either mobile or in-shop service works.";
export const jobSpec:JobSpec={specId:"spec_demo",revision:1,vertical:"auto_glass",status:"CONFIRMED",core:specCore,callBrief:{text:CALL_BRIEF,sha256:freezeSpecCore({text:CALL_BRIEF})},confirmation:{confirmedBy:"demo-user",confirmedAt:new Date().toISOString(),coreSha256:specHash}};
