import { beforeEach, describe, expect, it } from "vitest";
import { addDocument, addFollowUp, attachOffer, closeNegotiation, createNegotiation, recordApproval, recommend } from "./negotiation-service.js";
import { resetStore } from "./store.js";

const intake=()=>({negotiationType:"auto_glass" as const,objective:"Get a fair windshield quote",currentSituation:"Cash-pay replacement is needed",priorities:["safety","all-in price"],constraints:["written confirmation"],desiredOutcomeMinor:65000,walkAwayMinor:90000,deadline:null,supportingContext:"",vehicle:{year:2021,make:"Volkswagen",model:"Tiguan",vin:null,frontCamera:true},postalCode:"28202",sources:[{kind:"USER" as const,label:"test",addedAt:new Date().toISOString()}]});
const offer=(providerId="shop",total=70000)=>({quoteId:`q_${providerId}`,providerId,callId:`call_${providerId}`,specRevision:1,offerVersion:1,stage:"INITIAL" as const,currency:"USD" as const,lineItems:[{category:"BASE_GLASS_AND_INSTALL" as const,rawLabel:"glass",amountMinor:total-20000,status:"INCLUDED" as const,scope:{},provenanceIds:["p1"]},{category:"ADAS_CALIBRATION" as const,rawLabel:"calibration",amountMinor:15000,status:"INCLUDED" as const,scope:{},provenanceIds:["p2"]},{category:"TAX" as const,rawLabel:"tax",amountMinor:5000,status:"INCLUDED" as const,scope:{},provenanceIds:["p3"]}],totals:{statedAllInMinor:total,computedKnownMinor:total,taxStatus:"INCLUDED" as const,reconciliation:"MATCH" as const},terms:{validUntil:null,writtenConfirmation:true,warranty:"lifetime",appointmentWindow:"weekday"},comparability:"COMPARABLE" as const,redFlags:[]});
beforeEach(()=>resetStore());
describe("canonical negotiation lifecycle",()=>{
  it("creates intake with an estimated benchmark and strategy",()=>{const n=createNegotiation(intake());expect(n.state).toBe("intake");expect(n.benchmark.classification).toBe("ESTIMATED");expect(n.strategy.walkAwayMinor).toBe(90000)});
  it("merges document intake into the same durable spec",()=>{const n=createNegotiation(intake());const updated=addDocument(n.negotiationId,"Existing written quote: all-in price $720 with calibration.");expect(updated.intake.sources.at(-1)?.kind).toBe("DOCUMENT");expect(updated.events.at(-1)?.type).toBe("DOCUMENT_ADDED")});
  it("enforces confirmation and outbound-call approval",()=>{const n=createNegotiation(intake());expect(()=>recordApproval(n.negotiationId,"START_CALLS","go")).toThrow(/confirm/);recordApproval(n.negotiationId,"CONFIRM_SPEC","correct");expect(recordApproval(n.negotiationId,"START_CALLS","call three shops").state).toBe("calls_ready")});
  it("records an offer, evaluates risks, and recommends a counter",()=>{const n=createNegotiation(intake());recordApproval(n.negotiationId,"CONFIRM_SPEC","correct");recordApproval(n.negotiationId,"START_CALLS","approved");expect(attachOffer(n.negotiationId,offer()).state).toBe("offer_received");const result=recommend(n.negotiationId);expect(result.recommendation?.action).toBe("COUNTER");expect(result.state).toBe("recommendation_ready")});
  it("replaces the estimate with a verified local benchmark after two comparable providers",()=>{const n=createNegotiation(intake());recordApproval(n.negotiationId,"CONFIRM_SPEC","correct");recordApproval(n.negotiationId,"START_CALLS","approved");attachOffer(n.negotiationId,offer("shop-a",70000));const result=attachOffer(n.negotiationId,offer("shop-b",80000));expect(result.benchmark).toMatchObject({lowMinor:70000,typicalMinor:75000,highMinor:80000,classification:"VERIFIED"})});
  it("creates follow-ups idempotently",()=>{const n=createNegotiation(intake());const due=new Date(Date.now()+86_400_000).toISOString();addFollowUp(n.negotiationId,{idempotencyKey:"manager-callback",dueAt:due,note:"Call manager"});const result=addFollowUp(n.negotiationId,{idempotencyKey:"manager-callback",dueAt:due,note:"Call manager"});expect(result.followUps).toHaveLength(1)});
  it("requires explicit acceptance approval for a terminal accepted state",()=>{const n=createNegotiation(intake());expect(()=>closeNegotiation(n.negotiationId,"accepted")).toThrow(/ACCEPT_OFFER/);recordApproval(n.negotiationId,"ACCEPT_OFFER","accept written offer q1");expect(closeNegotiation(n.negotiationId,"accepted").state).toBe("accepted")});
});
