import { QuoteOffer, VerifiedFact, PolicyDecision } from "./domain.js";
import { createHash, randomUUID } from "node:crypto";

export function mintCompetitorOfferFact(quote: QuoteOffer, specCoreSha256: string, now = new Date()): VerifiedFact | null {
  if (quote.comparability !== "COMPARABLE" || quote.totals.reconciliation !== "MATCH" || quote.totals.statedAllInMinor == null) return null;
  if (quote.terms.validUntil && new Date(quote.terms.validUntil) < now) return null;
  if (quote.lineItems.some(li => li.provenanceIds.length === 0)) return null;
  const dollars = (quote.totals.statedAllInMinor / 100).toFixed(0);
  const calib = quote.lineItems.find(li => li.category === "ADAS_CALIBRATION" && li.status === "INCLUDED");
  return { factId: `fact_${randomUUID()}`, kind: "COMPETITOR_ALL_IN_OFFER", subjectProviderId: quote.providerId, amountMinor: quote.totals.statedAllInMinor, scopeHash: specCoreSha256 as VerifiedFact["scopeHash"], validUntil: quote.terms.validUntil, provenanceIds: quote.lineItems.flatMap(li => li.provenanceIds), allowedClaim: calib ? `I have a verified all-in quote of $${dollars} for the same vehicle, including ADAS calibration.` : `I have a verified quote of $${dollars} for the same vehicle.`, status: "ACTIVE" };
}
export interface LeverageRequest { callId: string; targetProviderId: string; desiredConcession: "PRICE_MATCH" | "WAIVE_FEE" | "TERM_IMPROVEMENT"; round: number }
export function requestLeverage(req: LeverageRequest, activeFacts: VerifiedFact[], priorRoundsThisCall: number, now = new Date()): PolicyDecision {
  const base = { decisionId: `dec_${randomUUID()}`, callId: req.callId, requested: `${req.desiredConcession} (round ${req.round})`, at: now.toISOString(), round: Math.min(Math.max(req.round, 1), 3) as 1|2|3 };
  if (priorRoundsThisCall >= 3) return { ...base, decision: "DENY", factIds: [], allowedStatement: null, denyReason: "Concession ladder exhausted (max 3 rounds). End the call politely." };
  const usable = activeFacts.filter(f => f.status === "ACTIVE" && f.subjectProviderId !== req.targetProviderId && (!f.validUntil || new Date(f.validUntil) >= now));
  if (!usable.length) return { ...base, decision: "DENY", factIds: [], allowedStatement: null, denyReason: "No active verified fact exists. You may NOT imply any competing offer." };
  const best = [...usable].sort((a,b) => (a.amountMinor ?? Infinity) - (b.amountMinor ?? Infinity))[0];
  return { ...base, decision: "ALLOW", factIds: [best.factId], allowedStatement: best.allowedClaim, denyReason: null };
}
export function computeKnownTotal(quote: Pick<QuoteOffer,"lineItems">) { const required = ["BASE_GLASS_AND_INSTALL","ADAS_CALIBRATION","TAX"]; let computedKnownMinor=0; const unknownCategories:string[]=[]; const seen=new Set<string>(); for(const li of quote.lineItems){seen.add(li.category); if(li.status==="INCLUDED"&&li.amountMinor!=null) computedKnownMinor+=li.amountMinor; if(li.status==="UNKNOWN"||(li.status==="INCLUDED"&&li.amountMinor==null&&required.includes(li.category))) unknownCategories.push(li.category)} for(const r of required) if(!seen.has(r)) unknownCategories.push(r); return {computedKnownMinor,isAllIn:!new Set(unknownCategories).size,unknownCategories:[...new Set(unknownCategories)]}; }
export function applyRedFlags(quote: QuoteOffer, comparableTotalsMinor:number[], vehicleHasCamera:boolean):QuoteOffer["redFlags"] { const flags:QuoteOffer["redFlags"]=[]; const calib=quote.lineItems.find(li=>li.category==="ADAS_CALIBRATION"); if(vehicleHasCamera&&(!calib||calib.status==="UNKNOWN"||calib.status==="EXCLUDED")) flags.push({code:"CALIBRATION_OMITTED",detail:"Vehicle has a windshield camera but calibration is not included in this quote."}); if(quote.totals.statedAllInMinor!=null&&comparableTotalsMinor.length>=2){const sorted=[...comparableTotalsMinor].sort((a,b)=>a-b); const median=sorted[Math.floor(sorted.length/2)]; if(quote.totals.statedAllInMinor<median*.7) flags.push({code:"SUSPICIOUS_LOWBALL",detail:`Quote is 30%+ below the median of comparable quotes ($${(median/100).toFixed(0)}).`})} if(quote.totals.reconciliation==="TOTAL_MISMATCH") flags.push({code:"TOTAL_MISMATCH",detail:"Stated total does not match the sum of itemized fees."}); return flags; }
const WEIGHTS={price:45,completeness:20,scopeQuality:15,schedule:10,terms:10};
export function rankQuotes(quotes:QuoteOffer[]){const eligible=quotes.filter(q=>q.comparability!=="NON_COMPARABLE"&&q.totals.statedAllInMinor!=null&&!q.redFlags.some(f=>f.code==="TOTAL_MISMATCH"));const prices=eligible.map(q=>q.totals.statedAllInMinor!);const min=Math.min(...prices),max=Math.max(...prices);return quotes.map(q=>{if(!eligible.includes(q))return{quoteId:q.quoteId,eligible:false,ineligibleReason:q.comparability==="NON_COMPARABLE"?"Scope not comparable":"No reconciled all-in total",score:null,componentScores:null,visiblePenalties:q.redFlags.map(f=>f.code)};const p=q.totals.statedAllInMinor!;const cs={price:(max===min?1:(max-p)/(max-min))*WEIGHTS.price,completeness:q.lineItems.filter(li=>li.status!=="UNKNOWN").length/Math.max(q.lineItems.length,1)*WEIGHTS.completeness,scopeQuality:(q.comparability==="COMPARABLE"?1:.6)*WEIGHTS.scopeQuality,schedule:(q.terms.appointmentWindow!=="UNKNOWN"?1:.5)*WEIGHTS.schedule,terms:(q.terms.writtenConfirmation?1:.5)*WEIGHTS.terms};return{quoteId:q.quoteId,eligible:true,ineligibleReason:null,score:Math.round((Object.values(cs).reduce((a,b)=>a+b,0)-q.redFlags.length*8)*10)/10,componentScores:cs,visiblePenalties:q.redFlags.map(f=>f.code)}}).sort((a,b)=>(b.score??-1)-(a.score??-1));}
export function freezeSpecCore(core:unknown){const canonical=JSON.stringify(core,Object.keys(core as object).sort());return createHash("sha256").update(canonical).digest("hex")}
