import "dotenv/config";
import { createHmac, timingSafeEqual } from "node:crypto";
import { randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import path from "node:path";
import Fastify from "fastify";
import { z } from "zod";
import { dispatchTool, TOOL_NAMES } from "./tools.js";
import { mutate, snapshot, store, type Turn } from "./store.js";
import { addDocument, addFollowUp, assertCallsApproved, attachOffer, closeNegotiation, createNegotiation, createNegotiationFromVin, currentNegotiation, getNegotiation, recordApproval, recordCall, recommend } from "./negotiation-service.js";
import { decodeVin } from "./vin-service.js";

const MAX_WEBHOOK_AGE_SECONDS=30*60;
export function verifyElevenLabsSignature(raw:Buffer,header:string|undefined,secret:string,now=Math.floor(Date.now()/1000)){if(!header||!secret)return false;const fields=Object.fromEntries(header.split(",").map(part=>part.trim().split("=",2)));const timestamp=Number(fields.t);const supplied=fields.v0;if(!Number.isFinite(timestamp)||Math.abs(now-timestamp)>MAX_WEBHOOK_AGE_SECONDS||!supplied)return false;const expected=createHmac("sha256",secret).update(`${timestamp}.${raw.toString("utf8")}`).digest("hex");try{return timingSafeEqual(Buffer.from(supplied,"hex"),Buffer.from(expected,"hex"))}catch{return false}}

type WebhookTurn={id?:string;role?:"agent"|"user";message?:string;text?:string;time_in_call_secs?:number};
type WebhookEvent={type:string;event_timestamp?:number;data?:{conversation_id?:string;status?:string;failure_reason?:string;transcript?:WebhookTurn[];conversation_initiation_client_data?:{dynamic_variables?:Record<string,string>}}};
function ingestWebhook(event:WebhookEvent){const data=event.data??{};const conversationId=String(data.conversation_id??"");const vars=data.conversation_initiation_client_data?.dynamic_variables??{};const callId=vars.call_id??conversationId;const providerId=vars.provider_id??"UNKNOWN";
  if(event.type==="call_initiation_failure"){mutate(s=>s.outcomes.push({callId,providerId,outcome:"DROPPED",reason:`call initiation failure: ${data.failure_reason??"unknown"}`,quoteId:null,callbackWindow:null,endedAt:new Date().toISOString()}));return}
  if(event.type!=="post_call_transcription")return;
  const finalTurnIds=new Set<string>();const finalTexts:string[]=[];
  mutate(s=>{for(const [index,item] of (data.transcript??[]).entries()){const turnId=item.id??`${conversationId}_turn_${index}`;finalTurnIds.add(turnId);const text=String(item.message??item.text??"");finalTexts.push(text);const turn:Turn={turnId,callId,conversationId,speaker:item.role==="agent"?"BUYER_AGENT":"PROVIDER",text};s.transcriptTurns[turnId]=turn}});
  for(const quote of store.quotes.filter(q=>q.callId===callId)){for(const item of quote.lineItems){for(const provenanceId of item.provenanceIds){const p=store.provenance[provenanceId];if(p&&!finalTurnIds.has(p.turnId)&&!finalTexts.some(t=>t.includes(p.transcriptExcerpt)||p.transcriptExcerpt.includes(t))){const detail=`${quote.quoteId}/${item.category}: provenance ${p.turnId} absent from final transcript`;console.warn(`[RECONCILE_WARN] ${detail}`);mutate(s=>s.timelineEvents.push({type:"RECONCILE_WARN",name:"missing_provenance_turn",callId,detail,at:new Date().toISOString()}))}}}}
  if(!store.outcomes.some(o=>o.callId===callId)){const reason=data.status==="done"?"conversation ended without close_call":`conversation ended with status ${data.status??"unknown"}`;mutate(s=>s.outcomes.push({callId,providerId,outcome:"DROPPED",reason,quoteId:null,callbackWindow:null,endedAt:new Date().toISOString()}))}
}

function jsonBody(body:unknown){if(Buffer.isBuffer(body))return JSON.parse(body.toString("utf8"));return body}
export function buildServer(env:NodeJS.ProcessEnv=process.env){const app=Fastify({logger:false,bodyLimit:1_000_000});app.addContentTypeParser("application/json",{parseAs:"buffer"},(_req,body,done)=>done(null,body));app.addHook("onSend",async(_req,reply,payload)=>{reply.header("access-control-allow-origin",env.FRONTEND_ORIGIN??"*");reply.header("access-control-allow-headers","content-type,x-tool-secret");reply.header("access-control-allow-methods","GET,POST,OPTIONS");return payload});app.options("*",async(_req,reply)=>reply.code(204).send());
  app.post<{Params:{toolName:string}}>("/tools/:toolName",async(req,reply)=>{const started=performance.now();if(req.headers["x-tool-secret"]!==env.TOOL_SHARED_SECRET)return reply.code(401).send({error:"unauthorized"});if(!TOOL_NAMES.includes(req.params.toolName as typeof TOOL_NAMES[number]))return reply.code(404).send({error:"unknown tool"});try{const raw=req.body as Buffer;const args=JSON.parse(raw.toString("utf8"));const result=dispatchTool(req.params.toolName,args);reply.header("server-timing",`tool;dur=${(performance.now()-started).toFixed(1)}`);return{ok:true,result}}catch(error){req.log.error(error);return reply.code(400).send({error:error instanceof Error?error.message:"tool failed",fallback:"Let me double-check and follow up."})}});
  app.post("/webhooks/elevenlabs",async(req,reply)=>{const raw=req.body as Buffer;const secret=env.ELEVENLABS_WEBHOOK_SECRET??env.TOOL_SHARED_SECRET??"";if(!verifyElevenLabsSignature(raw,req.headers["elevenlabs-signature"] as string|undefined,secret))return reply.code(401).send({error:"invalid or stale signature"});try{ingestWebhook(JSON.parse(raw.toString("utf8")));return{status:"received"}}catch{return reply.code(400).send({error:"invalid webhook"})}});
  app.setErrorHandler((error,_req,reply)=>{const message=error instanceof Error?error.message:"request failed";const status=error instanceof z.ZodError?422:message.includes("not found")?404:message.includes("required")||message.includes("before")?409:400;return reply.code(status).send({error:error instanceof z.ZodError?"validation failed":message,issues:error instanceof z.ZodError?error.issues:undefined})});
  app.post("/api/negotiations",async req=>createNegotiation(jsonBody(req.body)));
  app.get<{Params:{vin:string}}>("/api/vin/:vin",async req=>decodeVin(req.params.vin));
  app.post("/api/negotiations/from-vin",async req=>createNegotiationFromVin(jsonBody(req.body)));
  app.get<{Params:{id:string}}>("/api/negotiations/:id",async req=>getNegotiation(req.params.id));
  app.get("/api/negotiations/current",async(_req,reply)=>{const n=currentNegotiation();return n??reply.code(404).send({error:"no current negotiation"})});
  app.post<{Params:{id:string}}>("/api/negotiations/:id/documents",async req=>{const b=z.object({documentText:z.string(),label:z.string().optional()}).parse(jsonBody(req.body));return addDocument(req.params.id,b.documentText,b.label)});
  app.post<{Params:{id:string}}>("/api/negotiations/:id/approvals",async req=>{const b=z.object({action:z.enum(["CONFIRM_SPEC","START_CALLS","MAKE_COUNTEROFFER","ACCEPT_OFFER","SHARE_SENSITIVE_INFO","CONFIRM_AGREEMENT"]),details:z.string().min(1)}).parse(jsonBody(req.body));return recordApproval(req.params.id,b.action,b.details)});
  app.post<{Params:{id:string}}>("/api/negotiations/:id/calls",async(req,reply)=>{const b=z.object({provider:z.enum(["premium_chain","independent_lowballer","mobile_operator"]).default("premium_chain")}).parse(jsonBody(req.body));assertCallsApproved(req.params.id);if(!env.PERSONA_TO_NUMBER)throw new Error("PERSONA_TO_NUMBER is required");const callId=`call_${randomUUID()}`;recordCall(req.params.id,{callId,providerId:b.provider,conversationId:"pending",status:"IN_PROGRESS",outcome:null,reason:null,transcript:[]});const executable=path.resolve("node_modules/.bin/tsx");const child=spawn(executable,["scripts/run-call.ts","--persona",b.provider,"--phase","QUOTE_COLLECTION","--negotiation",req.params.id,"--call-id",callId],{cwd:process.cwd(),env:{...process.env,...env},stdio:["ignore","pipe","pipe"]});child.stdout.on("data",data=>console.log(`[call ${callId}] ${String(data).trim()}`));child.stderr.on("data",data=>console.error(`[call ${callId}] ${String(data).trim()}`));child.on("error",error=>recordCall(req.params.id,{callId,providerId:b.provider,conversationId:"pending",status:"FAILED",outcome:"DROPPED",reason:error.message,transcript:[]}));child.on("exit",code=>{if(code&&code!==0)recordCall(req.params.id,{callId,providerId:b.provider,conversationId:"pending",status:"FAILED",outcome:"DROPPED",reason:`call runner exited with code ${code}`,transcript:[]})});return reply.code(202).send({accepted:true,callId,provider:b.provider})});
  app.post<{Params:{id:string}}>("/api/negotiations/:id/offers",async req=>attachOffer(req.params.id,jsonBody(req.body)));
  app.post<{Params:{id:string}}>("/api/negotiations/:id/recommendation",async req=>recommend(req.params.id));
  app.post<{Params:{id:string}}>("/api/negotiations/:id/follow-ups",async req=>{const b=z.object({idempotencyKey:z.string().min(1),dueAt:z.string().datetime(),note:z.string().min(1)}).parse(jsonBody(req.body));return addFollowUp(req.params.id,b)});
  app.post<{Params:{id:string}}>("/api/negotiations/:id/close",async req=>{const b=z.object({outcome:z.enum(["accepted","walked_away","closed"])}).parse(jsonBody(req.body));return closeNegotiation(req.params.id,b.outcome)});
  app.get("/runs/current",async()=>({negotiation:currentNegotiation(),legacy:snapshot()}));app.get("/health",async()=>({ok:true,service:"the-negotiator",storeLoaded:true}));return app}
if(import.meta.url===`file://${process.argv[1]}`){const port=Number(process.env.PORT??3000);buildServer().listen({port,host:"0.0.0.0"}).then(()=>console.log(`Tool server listening on :${port}`)).catch(error=>{console.error(error);process.exit(1)})}
