import {createHmac} from "node:crypto";
import {afterEach,describe,expect,it} from "vitest";
import {buildServer,verifyElevenLabsSignature} from "./server.js";
import {store} from "./store.js";
const apps:ReturnType<typeof buildServer>[]=[];afterEach(async()=>{await Promise.all(apps.splice(0).map(a=>a.close()))});
describe("voice server security",()=>{it("rejects unauthenticated tools",async()=>{const app=buildServer({TOOL_SHARED_SECRET:"secret"});apps.push(app);expect((await app.inject({method:"POST",url:"/tools/get_call_brief",payload:{}})).statusCode).toBe(401)});it("serves authenticated shared tools",async()=>{const app=buildServer({TOOL_SHARED_SECRET:"secret"});apps.push(app);const response=await app.inject({method:"POST",url:"/tools/get_call_brief",headers:{"x-tool-secret":"secret"},payload:{}});expect(response.statusCode).toBe(200);expect(response.json().result.sha256).toHaveLength(64)});it("rejects stale webhook signatures",()=>{const body=Buffer.from("{}");const timestamp=100;const sig=createHmac("sha256","secret").update(`${timestamp}.{}`).digest("hex");expect(verifyElevenLabsSignature(body,`t=${timestamp},v0=${sig}`,"secret",2000)).toBe(false)});it("accepts current valid webhook signatures",()=>{const body=Buffer.from("{}");const timestamp=Math.floor(Date.now()/1000);const sig=createHmac("sha256","secret").update(`${timestamp}.{}`).digest("hex");expect(verifyElevenLabsSignature(body,`t=${timestamp},v0=${sig}`,"secret",timestamp)).toBe(true)})});
describe("tool latency",()=>{it("keeps local synchronous tools well below the 800ms target",async()=>{const app=buildServer({TOOL_SHARED_SECRET:"secret"});apps.push(app);const samples:number[]=[];for(let i=0;i<20;i++){const start=performance.now();const response=await app.inject({method:"POST",url:"/tools/get_call_brief",headers:{"x-tool-secret":"secret"},payload:{}});samples.push(performance.now()-start);expect(response.statusCode).toBe(200)}samples.sort((a,b)=>a-b);expect(samples[Math.floor(samples.length*.95)]).toBeLessThan(800)})});
describe("money boundary",()=>{it("rejects fractional cents from voice tools",async()=>{const app=buildServer({TOOL_SHARED_SECRET:"secret"});apps.push(app);const response=await app.inject({method:"POST",url:"/tools/log_quote_total",headers:{"x-tool-secret":"secret"},payload:{call_id:"c",provider_id:"p",turn_id:"t",turn_text:"total",total_minor:123.45}});expect(response.statusCode).toBe(400);expect(response.json().error).toContain("integer cents")})});
describe("post-call outcomes",()=>{it("records a dropped outcome when a completed transcript lacks close_call",async()=>{const secret="webhook-secret",callId=`test_${Date.now()}`;const app=buildServer({ELEVENLABS_WEBHOOK_SECRET:secret});apps.push(app);const payload={type:"post_call_transcription",data:{conversation_id:`conv_${callId}`,status:"done",conversation_initiation_client_data:{dynamic_variables:{call_id:callId,provider_id:"shop"}},transcript:[]}};const raw=JSON.stringify(payload),timestamp=Math.floor(Date.now()/1000),sig=createHmac("sha256",secret).update(`${timestamp}.${raw}`).digest("hex");const response=await app.inject({method:"POST",url:"/webhooks/elevenlabs",headers:{"content-type":"application/json","elevenlabs-signature":`t=${timestamp},v0=${sig}`},payload:raw});expect(response.statusCode).toBe(200);expect(store.outcomes.find(o=>o.callId===callId)).toMatchObject({outcome:"DROPPED",reason:"conversation ended without close_call"})})});
