import { randomUUID } from "node:crypto";
import type { CallOutcome, FeeCategory, ProvenanceAnchor, QuoteLineItem, QuoteOffer } from "./domain.js";
import { computeKnownTotal, requestLeverage } from "./policy.js";
import { jobSpec } from "./config.js";
import { mutate, store, type Turn } from "./store.js";

function anchor(turn:Turn,claimType:ProvenanceAnchor["claimType"]){if(!store.transcriptTurns[turn.turnId])throw new Error("provenance turn must exist before logging a claim");const p:ProvenanceAnchor={provenanceId:`prov_${randomUUID()}`,conversationId:turn.conversationId??turn.callId,turnId:turn.turnId,speaker:turn.speaker,transcriptExcerpt:turn.text,claimType,extractionMethod:"LIVE_TOOL",confidence:1};mutate(s=>{s.provenance[p.provenanceId]=p});return p.provenanceId}
export function recordTurn(callId:string,speaker:Turn["speaker"],text:string,conversationId?:string){const turn:Turn={turnId:`turn_${randomUUID()}`,callId,speaker,text,conversationId};mutate(s=>{s.transcriptTurns[turn.turnId]=turn});return turn}
export const tools={
  get_call_brief:()=>({text:jobSpec.callBrief!.text,sha256:jobSpec.callBrief!.sha256}),
  log_quote_item:(turn:Turn,category:FeeCategory,rawLabel:string,amountMinor:number|null,status:QuoteLineItem["status"],scope:Record<string,string>={})=>{if(amountMinor!=null&&(!Number.isInteger(amountMinor)||amountMinor<0))throw new Error("amount_minor must be nonnegative integer cents");return{category,rawLabel,amountMinor,status,scope,provenanceIds:[anchor(turn,"PRICE_LINE_ITEM")]} satisfies QuoteLineItem},
  log_quote_total:(turn:Turn,totalMinor:number)=>{if(!Number.isInteger(totalMinor)||totalMinor<0)throw new Error("total_minor must be nonnegative integer cents");return{totalMinor,provenanceId:anchor(turn,"TOTAL")}},
  log_term:(turn:Turn)=>anchor(turn,"TERM"),
  mark_unknown:(turn:Turn,category:FeeCategory)=>tools.log_quote_item(turn,category,"provider would not confirm",null,"UNKNOWN"),
  request_leverage:(callId:string,targetProviderId:string,desiredConcession:"PRICE_MATCH"|"WAIVE_FEE",round:number,prior:number)=>{const d=requestLeverage({callId,targetProviderId,desiredConcession,round},store.verifiedFacts,prior);mutate(s=>s.policyDecisions.push(d));return d},
  record_counteroffer:(initial:QuoteOffer,callId:string,totalMinor:number,turn:Turn):QuoteOffer=>{if(!Number.isInteger(totalMinor)||totalMinor<0||totalMinor>=initial.totals.statedAllInMinor!)throw new Error("counteroffer total must be lower nonnegative integer cents");const discount=initial.totals.statedAllInMinor!-totalMinor;const discountItem=tools.log_quote_item(turn,"DISCOUNT","verified competitor concession",discount,"INCLUDED");return{...initial,quoteId:`quote_${randomUUID()}`,callId,offerVersion:initial.offerVersion+1,stage:"NEGOTIATED",lineItems:[...initial.lineItems,discountItem],totals:{...initial.totals,statedAllInMinor:totalMinor,computedKnownMinor:totalMinor,reconciliation:"MATCH"},redFlags:[]}},
  close_call:(callId:string,providerId:string,outcome:CallOutcome["outcome"],reason:string,quoteId:string|null):CallOutcome=>{if(!reason.trim())throw new Error("structured close reason is required");const result={callId,providerId,outcome,reason,quoteId,callbackWindow:null,endedAt:new Date().toISOString()} satisfies CallOutcome;mutate(s=>s.outcomes.push(result));return result}
};

type VoiceArgs=Record<string,unknown>&{call_id?:string;provider_id?:string;turn_id?:string;turn_text?:string};
function voiceTurn(a:VoiceArgs){if(!a.call_id||!a.turn_id||!a.turn_text)throw new Error("call_id, turn_id, and turn_text are required");const existing=store.transcriptTurns[a.turn_id];if(existing)return existing;const t:Turn={turnId:a.turn_id,callId:a.call_id,speaker:"PROVIDER",text:a.turn_text};mutate(s=>{s.transcriptTurns[t.turnId]=t});return t}
function draft(callId:string,providerId:string){if(!callId||!providerId)throw new Error("call_id and provider_id are required");if(!store.drafts[callId])mutate(s=>{s.drafts[callId]={callId,providerId,lineItems:[],statedTotalMinor:null,terms:{}}});return store.drafts[callId]}
export function dispatchTool(name:string,a:VoiceArgs):unknown{const callId=String(a.call_id??"");const providerId=String(a.provider_id??"");switch(name){case"get_call_brief":return tools.get_call_brief();case"log_quote_item":{const item=tools.log_quote_item(voiceTurn(a),String(a.category) as FeeCategory,String(a.raw_label??a.category),a.amount_minor==null?null:Number(a.amount_minor),String(a.status) as QuoteLineItem["status"],(a.scope??{}) as Record<string,string>);mutate(s=>draft(callId,providerId).lineItems.push(item));return item}case"log_quote_total":{const result=tools.log_quote_total(voiceTurn(a),Number(a.total_minor));mutate(()=>{draft(callId,providerId).statedTotalMinor=Number(a.total_minor)});return result}case"log_term":{const result={provenanceId:tools.log_term(voiceTurn(a))};mutate(()=>{draft(callId,providerId).terms[String(a.term_name??"term")]=a.value});return result}case"mark_unknown":{const item=tools.mark_unknown(voiceTurn(a),String(a.category) as FeeCategory);mutate(()=>draft(callId,providerId).lineItems.push(item));return item}case"request_leverage":return tools.request_leverage(callId,providerId,String(a.desired_concession) as "PRICE_MATCH"|"WAIVE_FEE",Number(a.round??1),Number(a.prior_rounds??0));case"record_counteroffer":{const initial=store.quotes.find(q=>q.quoteId===a.initial_quote_id);if(!initial)throw new Error("initial quote not found");const offer=tools.record_counteroffer(initial,callId,Number(a.total_minor),voiceTurn(a));mutate(s=>s.quotes.push(offer));return offer}case"close_call":{let quoteId=a.quote_id?String(a.quote_id):null;if(String(a.outcome)==="QUOTED"&&!quoteId){const d=draft(callId,providerId),known=computeKnownTotal({lineItems:d.lineItems});const q:QuoteOffer={quoteId:`quote_${randomUUID()}`,providerId,callId,specRevision:1,offerVersion:1,stage:"INITIAL",currency:"USD",lineItems:d.lineItems,totals:{statedAllInMinor:d.statedTotalMinor,computedKnownMinor:known.computedKnownMinor,taxStatus:d.lineItems.some(i=>i.category==="TAX"&&i.status==="INCLUDED")?"INCLUDED":"UNKNOWN",reconciliation:d.statedTotalMinor!=null&&known.isAllIn&&d.statedTotalMinor===known.computedKnownMinor?"MATCH":"NOT_COMPARABLE_YET"},terms:{validUntil:null,writtenConfirmation:Boolean(d.terms.written_confirmation),warranty:"UNKNOWN",appointmentWindow:"UNKNOWN"},comparability:known.isAllIn?"COMPARABLE":"NON_COMPARABLE",redFlags:[]};quoteId=q.quoteId;mutate(s=>s.quotes.push(q))}return tools.close_call(callId,providerId,String(a.outcome) as CallOutcome["outcome"],String(a.reason??""),quoteId)}default:throw new Error(`unknown tool: ${name}`)}}
export const TOOL_NAMES=["get_call_brief","log_quote_item","log_quote_total","log_term","mark_unknown","request_leverage","record_counteroffer","close_call"] as const;
