/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationRouteImport } from './routes/recommendation'
import { Route as NegotiationRouteImport } from './routes/negotiation'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as IndexRouteImport } from './routes/index'

const RecommendationRoute = RecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiationRoute = NegotiationRouteImport.update({
  id: '/negotiation',
  path: '/negotiation',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/compare': typeof CompareRoute
  '/negotiation': typeof NegotiationRoute
  '/recommendation': typeof RecommendationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/compare': typeof CompareRoute
  '/negotiation': typeof NegotiationRoute
  '/recommendation': typeof RecommendationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/compare': typeof CompareRoute
  '/negotiation': typeof NegotiationRoute
  '/recommendation': typeof RecommendationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calls' | '/compare' | '/negotiation' | '/recommendation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calls' | '/compare' | '/negotiation' | '/recommendation'
  id:
    | '__root__'
    | '/'
    | '/calls'
    | '/compare'
    | '/negotiation'
    | '/recommendation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRoute
  CompareRoute: typeof CompareRoute
  NegotiationRoute: typeof NegotiationRoute
  RecommendationRoute: typeof RecommendationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendation': {
      id: '/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof RecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiation': {
      id: '/negotiation'
      path: '/negotiation'
      fullPath: '/negotiation'
      preLoaderRoute: typeof NegotiationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRoute,
  CompareRoute: CompareRoute,
  NegotiationRoute: NegotiationRoute,
  RecommendationRoute: RecommendationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
