import "dotenv/config";
import fs from "node:fs";
import {INTAKE_PROMPT,INTAKE_FIRST_MESSAGE,NEGOTIATION_PROMPT,NEGOTIATION_FIRST_MESSAGE,personaPrompt} from "../prompts.js";
import {TOOL_NAMES} from "../tools.js";
import {eleven,requireEnv} from "./elevenlabs-api.js";
type AgentSummary={agent_id:string;name:string};type ToolSummary={id:string;tool_config:{name:string}};
const NAMES={buyer_intake:"Negotiator Intake",buyer_negotiation:"Negotiator Negotiation",premium_chain:"Negotiator Premium Chain",independent_lowballer:"Negotiator Independent Lowballer",mobile_operator:"Negotiator Mobile Operator"} as const;
const voices={buyer:"pqHfZKP75CvOlQylNhV4",premium_chain:"cjVigY5qzO86Huf0OWal",independent_lowballer:"iP95p4xoKVk53GoZ742B",mobile_operator:"IKne3meq5aSn9XLyUdCD"};
const base={call_id:{type:"string",dynamic_variable:"call_id"},provider_id:{type:"string",dynamic_variable:"provider_id"},conversation_id:{type:"string",dynamic_variable:"system__conversation_id"}};
const evidence={turn_text:{type:"string",description:"The provider's exact words supporting this fact"}};
const factKeys=["SERVICE_RECOMMENDATION","BASE_PRICE","TOTAL","ALL_IN_SCOPE","TAX","ADAS_INCLUDED","ADAS_TYPE","ADAS_PRICE","GLASS_TYPE","MOBILE_SERVICE","MOLDINGS_CLIPS_SENSOR_KIT","DISPOSAL_ENVIRONMENTAL","SHOP_SUPPLIES","WARRANTY","AVAILABILITY","WRITTEN_CONFIRMATION","PRICE_CHANGE_CONDITIONS","REPRESENTATIVE","CALLBACK","QUOTE_REFERENCE","QUOTE_VALIDITY"];
const schemas:Record<string,{required:string[];properties:Record<string,unknown>}>= {
  get_call_brief:{required:["call_id","provider_id","conversation_id"],properties:{...base}},
  get_call_state:{required:["call_id","provider_id","conversation_id"],properties:{...base}},
  record_provider_answer:{required:["call_id","provider_id","conversation_id","turn_text","facts"],properties:{...base,...evidence,question_topic:{type:"string",description:"The one topic the agent had just asked about. Omit when the provider volunteered the information.",enum:factKeys},facts:{type:"array",description:"Every explicit fact contained in this one provider answer. Record multiple facts together and never infer an unstated value.",items:{type:"object",required:["key","status"],properties:{key:{type:"string",description:"Canonical conversation fact",enum:factKeys},status:{type:"string",description:"Whether the provider resolved, rejected, or left this fact ambiguous",enum:["KNOWN","NOT_APPLICABLE","REFUSED","AMBIGUOUS"]},value:{type:["string","null"],description:"Exact normalized meaning, while turn_text preserves the provider's words"},amount_minor:{type:["integer","null"],minimum:0,description:"Exact cents only when the provider stated an amount"},item_status:{type:"string",description:"Inclusion status for a monetary quote item; omit for non-price terms",enum:["INCLUDED","EXCLUDED","NOT_APPLICABLE","UNKNOWN"]},confirmed_correction:{type:"boolean",description:"True only after the provider explicitly resolves a conflict with an earlier value"}}}}}},
  get_prior_quote:{required:["call_id","provider_id","conversation_id"],properties:{...base}},
  log_quote_item:{required:["call_id","provider_id","conversation_id","turn_text","category","raw_label","status"],properties:{...base,...evidence,category:{type:"string",description:"Canonical fee category",enum:["BASE_GLASS_AND_INSTALL","ADAS_CALIBRATION","MOBILE_SERVICE","MOLDINGS_CLIPS_SENSOR_KIT","DISPOSAL_ENVIRONMENTAL","SHOP_SUPPLIES","TAX","DISCOUNT","OTHER"]},raw_label:{type:"string",description:"Provider's label for the fee"},amount_minor:{type:["integer","null"],description:"Exact amount in integer cents, or null if unknown"},status:{type:"string",description:"Whether the amount is included in the total",enum:["INCLUDED","EXCLUDED","NOT_APPLICABLE","UNKNOWN"]}}},
  log_quote_total:{required:["call_id","provider_id","conversation_id","turn_text","total_minor"],properties:{...base,...evidence,total_minor:{type:"integer",minimum:0,description:"Confirmed all-in total in integer cents"}}},
  log_term:{required:["call_id","provider_id","conversation_id","turn_text","term_name","value"],properties:{...base,...evidence,term_name:{type:"string",description:"Canonical term name"},value:{type:"string",description:"Exact confirmed term value"}}},
  mark_unknown:{required:["call_id","provider_id","conversation_id","turn_text","category"],properties:{...base,...evidence,category:{type:"string",description:"Unconfirmed fee category",enum:["BASE_GLASS_AND_INSTALL","ADAS_CALIBRATION","MOBILE_SERVICE","MOLDINGS_CLIPS_SENSOR_KIT","DISPOSAL_ENVIRONMENTAL","SHOP_SUPPLIES","TAX","DISCOUNT","OTHER"]}}},
  request_leverage:{required:["call_id","provider_id","conversation_id","desired_concession","round","prior_rounds"],properties:{...base,desired_concession:{type:"string",description:"Requested concession type",enum:["PRICE_MATCH","WAIVE_FEE"]},round:{type:"integer",description:"Current negotiation round",minimum:1},prior_rounds:{type:"integer",description:"Number of prior leverage rounds",minimum:0}}},
  record_counteroffer:{required:["call_id","provider_id","conversation_id","turn_text","initial_quote_id","total_minor"],properties:{...base,...evidence,initial_quote_id:{type:"string",description:"Quote being revised"},total_minor:{type:"integer",description:"Revised all-in total in integer cents",minimum:0}}},
  close_call:{required:["call_id","provider_id","conversation_id","outcome","reason"],properties:{...base,outcome:{type:"string",description:"Structured final call disposition",enum:["QUOTED","CALLBACK_REQUIRED","DECLINED","DROPPED"]},reason:{type:"string",description:"Concise factual close reason"}}}
};
async function ensureSecret(value:string){const listed=await eleven<{secrets?:{secret_id:string;name:string}[]}|{secret_id:string;name:string}[]>("/convai/secrets");const all=Array.isArray(listed)?listed:listed.secrets??[];const found=all.find(s=>s.name==="negotiator_tool_secret");if(found)return found.secret_id;return(await eleven<{secret_id:string}>("/convai/secrets",{method:"POST",body:JSON.stringify({type:"new",name:"negotiator_tool_secret",value})})).secret_id}
function toolConfig(name:string,baseUrl:string,secretId:string){return{type:"webhook",name,description:`Negotiator policy tool ${name}. Use exact provider evidence and dynamic identifiers. Never substitute model-generated data if it errors.`,response_timeout_secs:5,api_schema:{url:`${baseUrl}/tools/${name}`,method:"POST",request_body_schema:{type:"object",...schemas[name]},request_headers:{"x-tool-secret":{type:"secret",secret_id:secretId}}}}}
async function ensureTools(baseUrl:string,secretId:string){const listed=await eleven<{tools:ToolSummary[]}>("/convai/tools?page_size=100");const ids:Record<string,string>={};for(const name of TOOL_NAMES){const config=toolConfig(name,baseUrl,secretId);const found=listed.tools.find(t=>t.tool_config.name===name);if(found){await eleven(`/convai/tools/${found.id}`,{method:"PATCH",body:JSON.stringify({tool_config:config})});ids[name]=found.id}else{const created=await eleven<{id:string}>("/convai/tools",{method:"POST",body:JSON.stringify({tool_config:config})});ids[name]=created.id}}return ids}
function conversationConfig(prompt:string,voiceId:string,toolIds:string[],firstMessage:string,eagerness:"eager"|"normal"|"patient"="normal"){return{turn:{turn_timeout:12,turn_eagerness:eagerness},tts:{voice_id:voiceId,model_id:"eleven_turbo_v2",agent_output_audio_format:"ulaw_8000",optimize_streaming_latency:3,stability:.5,speed:1,similarity_boost:.8},asr:{user_input_audio_format:"ulaw_8000",quality:"high"},conversation:{max_duration_seconds:900},agent:{first_message:firstMessage,language:"en",disable_first_message_interruptions:false,dynamic_variables:{dynamic_variable_placeholders:{call_id:"call_demo",provider_id:"premium_chain",call_brief_text:"",phase:"QUOTE_COLLECTION",allowed_concessions:"none"}},prompt:{prompt,llm:"gemini-2.5-flash",temperature:.45,tool_ids:toolIds}}}}
async function ensureAgent(name:string,config:unknown,agents:AgentSummary[]){const platform_settings={overrides:{conversation_config_override:{agent:{prompt:{prompt:true}}}}};const found=agents.find(a=>a.name===name);if(found){await eleven(`/convai/agents/${found.agent_id}`,{method:"PATCH",body:JSON.stringify({name,conversation_config:config,platform_settings,tags:["negotiator","hackathon"]})});return found.agent_id}return(await eleven<{agent_id:string}>("/convai/agents/create",{method:"POST",body:JSON.stringify({name,conversation_config:config,platform_settings,tags:["negotiator","hackathon"]})})).agent_id}
function personaGreeting(id:string){return id==="premium_chain"?"Thanks for calling ClearView Auto Glass, this is Dana — how can I help?":id==="independent_lowballer"?"Rick's Auto Glass, yeah what do you need?":"GlassGo Mobile, this is Sam."}
async function main(){const env=requireEnv("ELEVENLABS_API_KEY","PUBLIC_BASE_URL","TOOL_SHARED_SECRET");const secretId=await ensureSecret(env.TOOL_SHARED_SECRET);const tools=await ensureTools(env.PUBLIC_BASE_URL.replace(/\/$/,""),secretId);const agents=(await eleven<{agents:AgentSummary[]}>("/convai/agents?page_size=100")).agents;const ids:Record<string,string>={};const intakeTools=["get_call_state","record_provider_answer","close_call"].map(name=>tools[name]);const negotiationTools=["get_prior_quote","request_leverage","record_counteroffer","close_call"].map(name=>tools[name]);ids.buyer_intake=await ensureAgent(NAMES.buyer_intake,conversationConfig(INTAKE_PROMPT,voices.buyer,intakeTools,INTAKE_FIRST_MESSAGE),agents);ids.buyer_negotiation=await ensureAgent(NAMES.buyer_negotiation,conversationConfig(NEGOTIATION_PROMPT,voices.buyer,negotiationTools,NEGOTIATION_FIRST_MESSAGE),agents);for(const id of ["premium_chain","independent_lowballer","mobile_operator"] as const){const eagerness=id==="independent_lowballer"?"eager":id==="mobile_operator"?"patient":"normal";ids[id]=await ensureAgent(NAMES[id],conversationConfig(personaPrompt(id),voices[id],[],personaGreeting(id),eagerness),agents)}fs.writeFileSync("agents.json",JSON.stringify(ids,null,2),{mode:0o600});console.log(JSON.stringify(ids,null,2))}
main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exit(1)});
