import "dotenv/config";
import fs from "node:fs";
import {BUYER_PROMPT,personaPrompt} from "../prompts.js";
import {TOOL_NAMES} from "../tools.js";
import {eleven,requireEnv} from "./elevenlabs-api.js";
type AgentSummary={agent_id:string;name:string};type ToolSummary={id:string;tool_config:{name:string}};
const NAMES={buyer:"Negotiator Buyer",premium_chain:"Negotiator Premium Chain",independent_lowballer:"Negotiator Independent Lowballer",mobile_operator:"Negotiator Mobile Operator"} as const;
const voices={buyer:"21m00Tcm4TlvDq8ikWAM",premium_chain:"ErXwobaYiN019PkySvjV",independent_lowballer:"pNInz6obpgDQGcFmaJgB",mobile_operator:"TxGEqnHWrfWFTfGW9XjX"};
const bodyProperties={call_id:{type:"string",description:"Dynamic call id"},provider_id:{type:"string",description:"Dynamic provider id"},turn_id:{type:"string",description:"Transcript turn id containing provider evidence"},turn_text:{type:"string",description:"Exact provider transcript turn"}};
async function ensureSecret(value:string){const listed=await eleven<{secrets?:{secret_id:string;name:string}[]}|{secret_id:string;name:string}[]>("/convai/secrets");const all=Array.isArray(listed)?listed:listed.secrets??[];const found=all.find(s=>s.name==="negotiator_tool_secret");if(found)return found.secret_id;return(await eleven<{secret_id:string}>("/convai/secrets",{method:"POST",body:JSON.stringify({type:"new",name:"negotiator_tool_secret",value})})).secret_id}
function toolConfig(name:string,baseUrl:string,secretId:string){return{type:"webhook",name,description:`Negotiator policy tool ${name}. Never substitute model-generated data if it errors.`,response_timeout_secs:2,api_schema:{url:`${baseUrl}/tools/${name}`,method:"POST",request_body_schema:{type:"object",required:["call_id","provider_id"],properties:bodyProperties},request_headers:{"x-tool-secret":{type:"secret",secret_id:secretId}}}}}
async function ensureTools(baseUrl:string,secretId:string){const listed=await eleven<{tools:ToolSummary[]}>("/convai/tools?page_size=100");const ids:string[]=[];for(const name of TOOL_NAMES){const config=toolConfig(name,baseUrl,secretId);const found=listed.tools.find(t=>t.tool_config.name===name);if(found){await eleven(`/convai/tools/${found.id}`,{method:"PATCH",body:JSON.stringify({tool_config:config})});ids.push(found.id)}else{const created=await eleven<{id:string}>("/convai/tools",{method:"POST",body:JSON.stringify({tool_config:config})});ids.push(created.id)}}return ids}
function conversationConfig(prompt:string,voiceId:string,toolIds:string[],firstMessage:string,eagerness:"eager"|"normal"|"patient"="normal"){return{turn:{turn_timeout:12,turn_eagerness:eagerness},tts:{voice_id:voiceId,model_id:"eleven_turbo_v2_5",agent_output_audio_format:"ulaw_8000"},asr:{user_input_audio_format:"ulaw_8000"},conversation:{max_duration_seconds:900},agent:{first_message:firstMessage,language:"en",disable_first_message_interruptions:false,dynamic_variables:{dynamic_variable_placeholders:{call_id:"call_demo",provider_id:"premium_chain",call_brief_text:"",phase:"QUOTE_COLLECTION",allowed_concessions:"none"}},prompt:{prompt,llm:"gemini-2.5-flash",temperature:0,tool_ids:toolIds}}}}
async function ensureAgent(name:string,config:unknown,agents:AgentSummary[]){const found=agents.find(a=>a.name===name);if(found){await eleven(`/convai/agents/${found.agent_id}`,{method:"PATCH",body:JSON.stringify({name,conversation_config:config,tags:["negotiator","hackathon"]})});return found.agent_id}return(await eleven<{agent_id:string}>("/convai/agents/create",{method:"POST",body:JSON.stringify({name,conversation_config:config,tags:["negotiator","hackathon"]})})).agent_id}
async function main(){const env=requireEnv("ELEVENLABS_API_KEY","PUBLIC_BASE_URL","TOOL_SHARED_SECRET");const secretId=await ensureSecret(env.TOOL_SHARED_SECRET);const toolIds=await ensureTools(env.PUBLIC_BASE_URL.replace(/\/$/,""),secretId);const agents=(await eleven<{agents:AgentSummary[]}>("/convai/agents?page_size=100")).agents;const ids:Record<string,string>={};ids.buyer=await ensureAgent(NAMES.buyer,conversationConfig(BUYER_PROMPT,voices.buyer,toolIds,"Hello, I'm an AI assistant calling on behalf of a customer about a windshield replacement quote. This call may be transcribed."),agents);for(const id of ["premium_chain","independent_lowballer","mobile_operator"] as const){const eagerness=id==="independent_lowballer"?"eager":id==="mobile_operator"?"patient":"normal";ids[id]=await ensureAgent(NAMES[id],conversationConfig(personaPrompt(id),voices[id],[],`${NAMES[id]}, how can I help?`,eagerness),agents)}fs.writeFileSync("agents.json",JSON.stringify(ids,null,2),{mode:0o600});console.log(JSON.stringify(ids,null,2))}
main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exit(1)});
