import "dotenv/config";
import fs from "node:fs";
import {randomUUID} from "node:crypto";
import {CALL_BRIEF,jobSpec} from "../config.js";
import {loadStore,mutate,snapshot,store} from "../store.js";
import {applyRedFlags,mintCompetitorOfferFact,rankQuotes} from "../policy.js";
import {specHash} from "../config.js";
import {buyerPrompt} from "../prompts.js";
import {eleven,requireEnv} from "./elevenlabs-api.js";
type Persona="premium_chain"|"independent_lowballer"|"mobile_operator";type Agents=Record<Persona|"buyer",string>;
function arg(name:string){const index=process.argv.indexOf(name);return index>=0?process.argv[index+1]:undefined}
async function waitForConversation(id:string){for(let attempt=0;attempt<120;attempt++){const value=await eleven<{status:string;transcript?:unknown[]}>(`/convai/conversations/${id}`);if(["done","failed"].includes(value.status))return value;await new Promise(r=>setTimeout(r,5000))}throw new Error("conversation polling timed out")}
async function call(persona:Persona,phase:string,agents:Agents,to:string){const phoneId=process.env.ELEVENLABS_PHONE_NUMBER_ID!;const inboundId=process.env.PERSONA_PHONE_NUMBER_ID??phoneId;if(inboundId===phoneId)console.warn("Using one phone-number ID for inbound persona assignment and buyer outbound caller; a second imported number is recommended.");await eleven(`/convai/phone-numbers/${inboundId}`,{method:"PATCH",body:JSON.stringify({agent_id:agents[persona]})});const callId=`call_${randomUUID()}`;const policyAllow=phase==="NEGOTIATION"&&store.verifiedFacts.length>0;const initiated=await eleven<{conversation_id:string|null}>("/convai/twilio/outbound-call",{method:"POST",body:JSON.stringify({agent_id:agents.buyer,agent_phone_number_id:phoneId,to_number:to,conversation_initiation_client_data:{dynamic_variables:{call_id:callId,provider_id:persona,call_brief_text:CALL_BRIEF,phase,allowed_concessions:jobSpec.core.schedule.flexible?"weekday/in-shop":"none"},conversation_config_override:{agent:{prompt:{prompt:buyerPrompt(persona,policyAllow)}}}}})});if(!initiated.conversation_id)throw new Error("ElevenLabs did not return conversation_id");const conversation=await waitForConversation(initiated.conversation_id);loadStore();console.log(JSON.stringify({conversation_id:initiated.conversation_id,status:conversation.status,run:snapshot()},null,2))}
function normalizeAndMint(){loadStore();const initial=store.quotes.filter(q=>q.stage==="INITIAL");for(const q of initial){q.redFlags=applyRedFlags(q,initial.filter(other=>other!==q).flatMap(other=>other.totals.statedAllInMinor==null?[]:[other.totals.statedAllInMinor]),true)}for(const q of initial){if(!store.verifiedFacts.some(f=>f.subjectProviderId===q.providerId&&f.amountMinor===q.totals.statedAllInMinor)){const fact=mintCompetitorOfferFact(q,specHash);if(fact)store.verifiedFacts.push(fact)}}mutate(s=>{s.ranking=rankQuotes(s.quotes)})}
function printGate(){loadStore();const initial=store.quotes.filter(q=>q.stage==="INITIAL");const negotiated=store.quotes.filter(q=>q.stage==="NEGOTIATED");const gate={threeOutcomes:store.outcomes.filter(o=>initial.some(q=>q.callId===o.callId)).length===3,verifiedFact:store.verifiedFacts.length>0,negotiatedLower:negotiated.some(n=>initial.some(i=>i.providerId===n.providerId&&n.totals.statedAllInMinor!<i.totals.statedAllInMinor!)),provenance:store.quotes.every(q=>q.lineItems.every(i=>i.provenanceIds.every(id=>Boolean(store.provenance[id]))))};console.log("VOICE GATE:",JSON.stringify({...gate,all:Object.values(gate).every(Boolean)},null,2));console.log("RANKING:",JSON.stringify(store.ranking,null,2))}
async function main(){requireEnv("ELEVENLABS_API_KEY","ELEVENLABS_PHONE_NUMBER_ID");if(!fs.existsSync("agents.json"))throw new Error("agents.json missing; run npm run provision first");const agents=JSON.parse(fs.readFileSync("agents.json","utf8")) as Agents;const to=arg("--to")??process.env.PERSONA_TO_NUMBER;if(!to)throw new Error("Provide --to +E164 or PERSONA_TO_NUMBER");if(process.argv.includes("--all")){for(const p of ["premium_chain","independent_lowballer","mobile_operator"] as Persona[])await call(p,"QUOTE_COLLECTION",agents,to);normalizeAndMint();const initial=store.quotes.filter(q=>q.stage==="INITIAL"&&q.totals.reconciliation==="MATCH").sort((a,b)=>b.totals.statedAllInMinor!-a.totals.statedAllInMinor!)[0];if(initial)await call(initial.providerId as Persona,"NEGOTIATION",agents,to);normalizeAndMint();printGate();return}const persona=(arg("--persona")??"premium_chain") as Persona;await call(persona,arg("--phase")??"QUOTE_COLLECTION",agents,to)}
main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exit(1)});
