import "dotenv/config";
import fs from "node:fs";
import {randomUUID} from "node:crypto";
import {CALL_BRIEF,jobSpec} from "../config.js";
import {loadStore,mutate,store} from "../store.js";
import {applyRedFlags,mintCompetitorOfferFact,rankQuotes} from "../policy.js";
import {specHash} from "../config.js";
import {buyerPrompt} from "../prompts.js";
import {eleven,requireEnv} from "./elevenlabs-api.js";
import {assertCallsApproved,attachOffer,recommend,recordCall} from "../negotiation-service.js";
type Persona="premium_chain"|"independent_lowballer"|"mobile_operator";type Agents=Record<Persona|"buyer_intake"|"buyer_negotiation",string>;
function arg(name:string){const index=process.argv.indexOf(name);return index>=0?process.argv[index+1]:undefined}
type Conversation={status:string;transcript?:Array<{id?:string;role?:"agent"|"user";message?:string|null;time_in_call_secs?:number}>;metadata?:{start_time_unix_secs?:number;call_duration_secs?:number}};
async function waitForConversation(id:string){for(let attempt=0;attempt<120;attempt++){const value=await eleven<Conversation>(`/convai/conversations/${id}`);if(["done","failed"].includes(value.status))return value;await new Promise(r=>setTimeout(r,5000))}throw new Error("conversation polling timed out")}
async function call(persona:Persona,phase:"QUOTE_COLLECTION"|"NEGOTIATION",agents:Agents,to:string,negotiationId:string){const phoneId=process.env.ELEVENLABS_PHONE_NUMBER_ID!;const inboundId=process.env.PERSONA_PHONE_NUMBER_ID;if(inboundId)await eleven(`/convai/phone-numbers/${inboundId}`,{method:"PATCH",body:JSON.stringify({agent_id:agents[persona]})});else console.log("Human shop-roleplay mode: persona phone assignment skipped.");const callId=arg("--call-id")??`call_${randomUUID()}`;const policyAllow=phase==="NEGOTIATION"&&store.verifiedFacts.length>0;const buyerAgentId=phase==="NEGOTIATION"?agents.buyer_negotiation:agents.buyer_intake;const initiated=await eleven<{conversation_id:string|null}>("/convai/twilio/outbound-call",{method:"POST",body:JSON.stringify({agent_id:buyerAgentId,agent_phone_number_id:phoneId,to_number:to,conversation_initiation_client_data:{dynamic_variables:{call_id:callId,negotiation_id:negotiationId,provider_id:persona,call_brief_text:CALL_BRIEF,phase,allowed_concessions:jobSpec.core.schedule.flexible?"weekday/in-shop":"none"},conversation_config_override:{agent:{prompt:{prompt:buyerPrompt(persona,phase,policyAllow)}}}}})});if(!initiated.conversation_id)throw new Error("ElevenLabs did not return conversation_id");recordCall(negotiationId,{callId,providerId:persona,conversationId:initiated.conversation_id,status:"IN_PROGRESS",outcome:null,reason:null,transcript:[]});const conversation=await waitForConversation(initiated.conversation_id);loadStore();const outcome=store.outcomes.find(o=>o.callId===callId);recordCall(negotiationId,{callId,providerId:persona,conversationId:initiated.conversation_id,status:conversation.status==="done"?"COMPLETE":"FAILED",outcome:outcome?.outcome??(conversation.status==="failed"?"DROPPED":null),reason:outcome?.reason??null,startedAt:conversation.metadata?.start_time_unix_secs?new Date(conversation.metadata.start_time_unix_secs*1000).toISOString():undefined,endedAt:new Date().toISOString(),transcript:conversation.transcript??[]});console.log(JSON.stringify({conversation_id:initiated.conversation_id,call_id:callId,status:conversation.status,outcome,draft:store.drafts[callId],quote:store.quotes.find(q=>q.callId===callId)},null,2))}
function normalizeAndMint(negotiationId:string){loadStore();const initial=store.quotes.filter(q=>q.stage==="INITIAL");for(const q of initial){q.redFlags=applyRedFlags(q,initial.filter(other=>other!==q).flatMap(other=>other.totals.statedAllInMinor==null?[]:[other.totals.statedAllInMinor]),true)}for(const q of initial){if(!store.verifiedFacts.some(f=>f.subjectProviderId===q.providerId&&f.amountMinor===q.totals.statedAllInMinor)){const fact=mintCompetitorOfferFact(q,specHash);if(fact)store.verifiedFacts.push(fact)}}mutate(s=>{s.ranking=rankQuotes(s.quotes)});const negotiation=store.negotiations[negotiationId];for(const quote of store.quotes){if(!negotiation.offers.some(o=>o.quoteId===quote.quoteId))attachOffer(negotiationId,quote)}}
function printGate(){loadStore();const initial=store.quotes.filter(q=>q.stage==="INITIAL");const negotiated=store.quotes.filter(q=>q.stage==="NEGOTIATED");const gate={threeOutcomes:store.outcomes.filter(o=>initial.some(q=>q.callId===o.callId)).length===3,verifiedFact:store.verifiedFacts.length>0,negotiatedLower:negotiated.some(n=>initial.some(i=>i.providerId===n.providerId&&n.totals.statedAllInMinor!<i.totals.statedAllInMinor!)),provenance:store.quotes.every(q=>q.lineItems.every(i=>i.provenanceIds.every(id=>Boolean(store.provenance[id]))))};console.log("VOICE GATE:",JSON.stringify({...gate,all:Object.values(gate).every(Boolean)},null,2));console.log("RANKING:",JSON.stringify(store.ranking,null,2))}
async function main(){requireEnv("ELEVENLABS_API_KEY","ELEVENLABS_PHONE_NUMBER_ID");const negotiationId=arg("--negotiation")??store.currentNegotiationId;if(!negotiationId)throw new Error("Create a negotiation and provide --negotiation <id> before calling");assertCallsApproved(negotiationId);if(!fs.existsSync("agents.json"))throw new Error("agents.json missing; run npm run provision first");const agents=JSON.parse(fs.readFileSync("agents.json","utf8")) as Agents;if(!agents.buyer_intake||!agents.buyer_negotiation)throw new Error("separate intake/negotiation agents are missing; run npm run provision");const to=arg("--to")??process.env.PERSONA_TO_NUMBER;if(!to)throw new Error("Provide --to +E164 or PERSONA_TO_NUMBER");if(process.argv.includes("--all")){for(const p of ["premium_chain","independent_lowballer","mobile_operator"] as Persona[])await call(p,"QUOTE_COLLECTION",agents,to,negotiationId);normalizeAndMint(negotiationId);const initial=store.quotes.filter(q=>q.stage==="INITIAL"&&q.totals.reconciliation==="MATCH").sort((a,b)=>b.totals.statedAllInMinor!-a.totals.statedAllInMinor!)[0];if(initial)await call(initial.providerId as Persona,"NEGOTIATION",agents,to,negotiationId);normalizeAndMint(negotiationId);recommend(negotiationId);printGate();return}const persona=(arg("--persona")??"premium_chain") as Persona;const phase=(arg("--phase")??"QUOTE_COLLECTION") as "QUOTE_COLLECTION"|"NEGOTIATION";await call(persona,phase,agents,to,negotiationId);normalizeAndMint(negotiationId)}
main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exit(1)});
